name: Fahchen's blog
description: In FREEDOM we trust
meta_description: In FREEDOM we trust.

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 7
baseurl: /
permalink: /:month-:day-:year/:title.html
domain_name: 'http://fahchen.me'
google_analytics: 'UA-36499516-2'

# Details for the RSS feed generator
url:            'http://fahchen.me'
author:         'Phil Chen'
author_bio: In FREEDOM we trust.

