name: Fahchen's blog
description: 一个地方写点东西
meta_description: 一个地方写点东西

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 7
baseurl: /
permalink: /:month-:day-:year/:title.html
domain_name: 'http://fahchen.me'
google_analytics: 'UA-61511673-1'

# Details for the RSS feed generator
url:            'http://fahchen.me'
author:         'Phil Chen'
author_bio: 除了必不可少的，我一无所需。

